In [1]:
import pandas as pd
import numpy as np
import re
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('corpus')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading corpus: Package 'corpus' not found in index

False

In [2]:
pd.set_option('display.max_columns', None) #to check all the col
df = pd.read_csv('IMDBdata_MainData.csv')
df = df.dropna(subset=['Title', 'Genre', 'Writer', 'Actors', 'Plot', 'Director']) # remove nan rows of interested cols
df = df.reset_index(drop=True) # reset index
df

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Country,Awards,Poster,Ratings.Source,Ratings.Value,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response,tomatoURL
0,Saving Christmas,2014,PG,14 Nov 2014,80 min,"Comedy, Family",Darren Doane,"Darren Doane, Cheston Hervey","Kirk Cameron, Darren Doane, Bridgette Cameron,...",Kirk is enjoying the annual Christmas party ex...,English,USA,4 wins & 2 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,1.6/10,18.0,1.6,"12,686",tt4009460,movie,03 Nov 2015,"$2,778,297",IPD/Samuel Goldwyn Films,http://www.savingchristmas.com/,True,http://www.rottentomatoes.com/m/kirk_camerons_...
1,Superbabies: Baby Geniuses 2,2004,PG,27 Aug 2004,88 min,"Comedy, Family, Sci-Fi",Bob Clark,"Steven Paul (story), Gregory Poppen (screenplay)","Jon Voight, Scott Baio, Vanessa Angel, Skyler ...",A group of smart-talking toddlers find themsel...,English,"Germany, UK, USA",13 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,2.0/10,9.0,2.0,"26,376",tt0270846,movie,04 Jan 2005,"$9,016,422",Sony,http://www.sonypictures.com/movies/superbabies...,True,http://www.rottentomatoes.com/m/super_babies_b...
2,Daniel der Zauberer,2004,NOT RATED,12 Aug 2004,81 min,"Comedy, Crime, Fantasy",Ulli Lommel,Ulli Lommel (screenplay),"Daniel Küblböck, Ulli Lommel, Rudolf Waldemar ...","Evil assassins want to kill Daniel Kublbock, t...",German,Germany,NaN,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,1.9/10,NaN,1.9,"13,060",tt0421051,movie,NaN,NaN,NaN,NaN,True,http://www.rottentomatoes.com/m/daniel_der_zau...
3,Manos: The Hands of Fate,1966,NOT RATED,15 Nov 1966,70 min,Horror,Harold P. Warren,Harold P. Warren (screenplay),"Tom Neyman, John Reynolds, Diane Adelson, Haro...",A family gets lost on the road and stumbles up...,English,USA,NaN,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,1.9/10,NaN,1.9,"31,768",tt0060666,movie,07 Oct 2003,NaN,Sinister Cinema,NaN,True,http://www.rottentomatoes.com/m/manos-the-hand...
4,Pledge This!,2006,R,NaN,91 min,Comedy,"William Heins, Strathford Hamilton","Cheryl Guerriero, Anna Obropta","Paris Hilton, Paula Garcés, Sarah Carter, Simo...","At South Beach University, a beautiful sororit...",English,USA,1 nomination.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,1.9/10,NaN,1.9,"15,828",tt0417056,movie,19 Dec 2006,NaN,Freestyle Releasing,NaN,True,http://www.rottentomatoes.com/m/national_lampo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5205,Cavite,2005,NOT RATED,12 Mar 2005,80 min,Thriller,"Neill Dela Llana, Ian Gamazon","Neill Dela Llana, Ian Gamazon","Ian Gamazon, Edwin Lagda, Edgar Tancangco, Nor...","Flying back to his home country, an American m...","English, Filipino, Tagalog","Philippines, USA",4 wins & 1 nomination.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,6.3/10,64.0,6.3,596,tt0428303,movie,08 Aug 2006,NaN,Gorilla Films,http://www.cavitemovie.com,True,http://www.rottentomatoes.com/m/1162654-cavite/
5206,The Mongol King,2005,PG-13,23 Apr 2005,84 min,"Drama, Crime",Anthony Vallone,"Richard Jewell, Robert Morgan, Anthony Vallone","John Considine, Gerry Cooper, Carey Crim, Jess...",While writing a term paper a woman gets involv...,English,USA,NaN,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,7.9/10,NaN,7.9,37,tt0430371,movie,NaN,NaN,NaN,NaN,True,NaN
5207,Signed Sealed Delivered,2013,NaN,12 Oct 2013,87 min,"Comedy, Drama",Scott Smith,"Martha Williamson, Brandi Harkonen (story editor)","Eric Mabius, Kristin Booth, Crystal Lowe, Geof...",A two-hour backdoor pilot of the TV series wit...,English,Canada,1 nomination.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,7.6/10,NaN,7.6,771,tt3000844,movie,NaN,NaN,NaN,NaN,True,NaN
5208,Shanghai Calling,2012,PG-13,08 Feb 2013,100 min,"Comedy, Drama, Romance",Daniel Hsia,Daniel Hsia,"Le Geng, Daniel Henney, Sean Gallagher, Bill M...",A New York attorney is sent to Shanghai on bus...,"English, Mandarin, Shanghainese","USA, China",3 wins & 1 nomination.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,6.3/10,45.0,6.3,"1,367",tt2070597,movie,16 Sep 2013,NaN,Starz Media,http://shanghaicalling.com/,True,http://www.rottentomatoes.com/m/shanghai_calling/
5209,A Plague So Pleasant,2013,NaN,26 Jan 2013,76 min,"Drama, Horror, Thriller","Benjamin Roberds, Jordan Reyes",Benjamin Roberds,"Eva Boehnke, David Chandler, Maxwell Moody",A surreal take on the zombie genre.,English,USA,NaN,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,6.2/10,NaN,6.2,40,tt2107644,movie,NaN,NaN,NaN,http://howtobeazombie.com/,True,NaN

In [3]:
#pre-process

In [4]:
stopwords = nltk.corpus.stopwords.words('english')

In [5]:
def clean_text(text):
    text = text.lower() # turn text to lowercase
    text = re.sub('[^a-zA-Z]', ' ', text) # remove non-character
    text = re.sub('\s+', ' ', text) # replace special space with one-space
    return text

def text_tokenize(text):
    text = clean_text(text)
    text_tokenized = nltk.word_tokenize(text) # tokenize word
    last_val = [i for i in text_tokenized if i not in stopwords or len(i)>=3] # remove stopwords and word that its length is lwoer than 3
    return last_val

def sep_val(val):
    # this try-except is for the data that have only 1 element or something we cant split 
    try:
        val = val.split(',')
    except:
        val = val
    last_val = [i.lower().replace(' ', '') for i in val]
    return last_val

In [6]:
# df.loc[0,['Title', 'Genre', 'Writer', 'Actors', 'Director', 'Plot']] # just check single row

In [7]:
# optional no need to create new
new_df = pd.DataFrame(data=df['Title']) # create new dataframe for cleaned data
new_df

                             Title
0                 Saving Christmas
1     Superbabies: Baby Geniuses 2
2              Daniel der Zauberer
3         Manos: The Hands of Fate
4                     Pledge This!
...                            ...
5205                        Cavite
5206               The Mongol King
5207       Signed Sealed Delivered
5208              Shanghai Calling
5209          A Plague So Pleasant

[5210 rows x 1 columns]

In [8]:
new_df['genre'] = df['Genre'].apply(sep_val)
new_df['writer'] = df['Writer'].apply(sep_val)
new_df['actors'] = df['Actors'].apply(sep_val)
new_df['director'] = df['Director'].apply(sep_val)
new_df['plot'] = df['Plot'].apply(text_tokenize)

In [9]:
new_df.head()

,Title,genre,writer,actors,director,plot
0,Saving Christmas,"[comedy, family]","[darrendoane, chestonhervey]","[kirkcameron, darrendoane, bridgettecameron, b...",[darrendoane],"[kirk, enjoying, the, annual, christmas, party..."
1,Superbabies: Baby Geniuses 2,"[comedy, family, sci-fi]","[stevenpaul(story), gregorypoppen(screenplay)]","[jonvoight, scottbaio, vanessaangel, skylershaye]",[bobclark],"[group, smart, talking, toddlers, find, themse..."
2,Daniel der Zauberer,"[comedy, crime, fantasy]",[ullilommel(screenplay)],"[danielküblböck, ullilommel, rudolfwaldemarbre...",[ullilommel],"[evil, assassins, want, kill, daniel, kublbock..."
3,Manos: The Hands of Fate,[horror],[haroldp.warren(screenplay)],"[tomneyman, johnreynolds, dianeadelson, harold...",[haroldp.warren],"[family, gets, lost, the, road, and, stumbles,..."
4,Pledge This!,[comedy],"[cherylguerriero, annaobropta]","[parishilton, paulagarcés, sarahcarter, simonrex]","[williamheins, strathfordhamilton]","[south, beach, university, beautiful, sorority..."

In [10]:
columns = ['genre', 'writer', 'actors', 'director', 'plot']
l = [] # create empty list for cleaned+sum of all input
for i in range(len(new_df)):
    words = ""
    for col in columns:
        words += " ".join(new_df[col][i]) + " "
        # 1st " " is for space between data in col
        # 2nd " " is for space between col
    l.append(words)

In [11]:
new_df['cleaned_input'] = l
new_df.head()

,Title,genre,writer,actors,director,plot,cleaned_input
0,Saving Christmas,"[comedy, family]","[darrendoane, chestonhervey]","[kirkcameron, darrendoane, bridgettecameron, b...",[darrendoane],"[kirk, enjoying, the, annual, christmas, party...",comedy family darrendoane chestonhervey kirkca...
1,Superbabies: Baby Geniuses 2,"[comedy, family, sci-fi]","[stevenpaul(story), gregorypoppen(screenplay)]","[jonvoight, scottbaio, vanessaangel, skylershaye]",[bobclark],"[group, smart, talking, toddlers, find, themse...",comedy family sci-fi stevenpaul(story) gregory...
2,Daniel der Zauberer,"[comedy, crime, fantasy]",[ullilommel(screenplay)],"[danielküblböck, ullilommel, rudolfwaldemarbre...",[ullilommel],"[evil, assassins, want, kill, daniel, kublbock...",comedy crime fantasy ullilommel(screenplay) da...
3,Manos: The Hands of Fate,[horror],[haroldp.warren(screenplay)],"[tomneyman, johnreynolds, dianeadelson, harold...",[haroldp.warren],"[family, gets, lost, the, road, and, stumbles,...",horror haroldp.warren(screenplay) tomneyman jo...
4,Pledge This!,[comedy],"[cherylguerriero, annaobropta]","[parishilton, paulagarcés, sarahcarter, simonrex]","[williamheins, strathfordhamilton]","[south, beach, university, beautiful, sorority...",comedy cherylguerriero annaobropta parishilton...

In [12]:
# feature extraction

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

In [14]:
features = vectorizer.fit_transform(new_df['cleaned_input'])

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
cosine_sim = cosine_similarity(features, features) # cosine between features and features

In [17]:

# it will be something like

#             A          B          C

#    A       1          a          b

#    B       c          1          d

#    C       e          f           1

#    a, b, c, d, e, f --> the similarity between that row and col

#    a diagonal is 1 because row and col is the same
   
#    if we compare it to itself, the similarity will be 1

In [18]:
def recommender(title):
    print(f'Movie : {title}')
    print('Recommend : ')
    # find index of title in new_df
    idx = new_df['Title'][new_df['Title'] == title].index[0] # idx -> index of new_df['Title'] where new_df['Title'] == title
    # find the most similar of idx
    score = pd.Series(cosine_sim[idx]).sort_values(ascending=False)
    # get index of top10 simil 
    top10 = list(score.iloc[1:11].index) # 1-11 because 0 is itself
#     print(top10)
    
    for i in range(len(top10)):
        # find title in new_df by index
        print(i+1,".", new_df['Title'][top10[i]])
    return " finish ૮ ˶ᵔ ᵕ ᵔ˶ ა "

In [19]:
movie_name = 'Harry Potter and the Half-Blood Prince'
recommender(movie_name)

Movie : Harry Potter and the Half-Blood Prince
Recommend :
1 . Harry Potter and the Deathly Hallows: Part 2
2 . Harry Potter and the Order of the Phoenix
3 . Harry Potter and the Prisoner of Azkaban
4 . Harry Potter and the Chamber of Secrets
5 . Sinbad: Legend of the Seven Seas
6 . The Polar Express
7 . Harry Potter and the Sorcerer's Stone
8 . The Chronicles of Narnia: The Voyage of the Dawn Treader
9 . The Pirates! Band of Misfits
10 . Diary of a Wimpy Kid

' finish ૮ ˶ᵔ ᵕ ᵔ˶ ა '